### ISSUE TITLE
Review call data estimation issue

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-gsn-provider#33]
> Call data gas estimation issue - if call data is bigger than certain value, transaction will fail and relayer will lose money (they said it is a critical issue)

This actually needs to be fixed on the tabookey-gasless repo, on the relayer code. Reported by CryptoManiacs team.

**Comment by nventuro** [comment]
https://github.com/tabookey/tabookey-gasless/pull/215 addressed this: we should release an updated version of the relayer.
