### ISSUE TITLE
Finding relayer

### ISSUE THREAD

**Issue by datgrog** [OpenZeppelin/openzeppelin-gsn-provider#41]
Hello there,

I'm learning GSN on openzeppelin and even if I think I got the whole idea, at some point the [documentation](https://docs.openzeppelin.com/openzeppelin/gsn/what-is-the-gsn) says  

> One of RelayHub’s jobs is to act as a, well, hub for all relayers: they will advertise their services on this contract, and your **users will query it to find the relayer** that best suits their purposes.

How exactly do get a list of all relayer for a given `RelayHub` contract?
I read somewhere that in fact to have an up to date list of relayers, one should listen `RelayHub`'s events and create the list himself from it. 

If my statement is true, well, perhaps updating this part of the documentation would be great.
Also, is there any analytics/monitoring website for this contract ? I only found [explore.duneanalytics](https://explore.duneanalytics.com/public/dashboards/9aUVYdNsXB8HmgpeALDOx0g42R8LD4Ns9ZoknrfD) but it feels wrong as latest points are always old from several days.

**Comment by abcoathup** [comment]
Hi @datgrog,

Would you mind posting this question in the Community Forum: https://forum.openzeppelin.com/, that way the entire community can help answer your question rather than just those watching this repo.  Thanks.
